package com.champaca.inventorydata.model

enum class Species(val longName: String) {
    AF("AFROMOSIA"),
    AH("ASH"),
    AP("APA"),
    BG("BUBINGA"),
    BE("BEECH"),
    BL("BILINGA"),
    BR("BIRCH"),
    CH("CHERRY"),
    DA("DEANG"),
    DG("DOUGLAS"),
    DS("DOUSSIE"),
    EU("EUCALIPTUS"),
    HK("HINOKI"),
    HM("HMR"),
    IP("IPE"),
    IR("IROKO"),
    JA("JATOBA"),
    KK("KOKKO"),
    KR("KAURI"),
    LP("LUMPOR"),
    MA("MUNPLA"),
    MH("MAHOGANY"),
    MK("MAKHA"),
    MP("MAPLE"),
    MX("MIX WOOD"),
    NE("NON TEAK"),
    NR("NARA"),
    NT("NT TEAK"),
    OA("OAK"),
    OV("OVENGOL"),
    PA("PRADU AFRICA"),
    PB("PACHYLOBA"),
    PI("PINE"),
    PL("PRADU LAO"),
    PM("PRADU MYANMAR"),
    PN("PINE"),
    PT("PT TEAK"),
    PW("PLYWOOD"),
    PY("PLYWOOD"),
    RF("ROKFAH"),
    RO("RED OAK"),
    RP("RUSSIAN PLYWOOD"),
    RW("RED WOOD"),
    SD("SADAO"),
    SP("SIPO"),
    ST("SATHORN"),
    TB("TABAK"),
    TE("TEAK"),
    TH("TAKIEN HIN"),
    TK("TAKIEN"),
    TL("TALI"),
    TN("TENG"),
    TT("TAKIEN THONG"),
    TY("TAKIEN YUONG"),
    WE("WENGE"),
    WN("WALNUT"),
    WO("WHITE OAK"),
    YA("YANG");
}