package com.champaca.inventorydata.pile

enum class PileError {
    PILE_NOT_FOUND,
    PILE_CODE_EXIST,
    UNABLE_TO_EDIT_PILE_BECAUSE_BEEN_USED,
    UNABLE_TO_REMOVE_PILE_BECAUSE_BEEN_USED,
    UNABLE_TO_UNDO_BECAUSE_FIRST_TRANSACTION,
    NO_ITEMS_TO_BE_RECEIVED,
    PALLET_NOT_FOUND,
    NON_EXISTING_MATCODE,
    LOT_HAS_ZERO_AMOUNT,
    WMS_VALIDATION_ERROR,
    PILE_HAS_BEEN_RECEIVED,
    NO_GOOD_RECEIPT_LINKS,
    LOCATION_NOT_FOUND,
    NO_TRANSFER_GOOD_MOVEMENT,
    INTERMEDIATE_GOOD_MOVEMENT_ID_NOT_FOUND,
    LOTS_ARE_OVERPICKED,
    EXCEEDING_TRANSFERRED_ITEM,
    GOOD_MOVEMENT_IS_NOT_APPROVED,
    UNABLE_TO_PICK_BECAUSE_NOT_IN_LOCATION,
    PILE_HAS_BEEN_COUNTED,
    INVALID_REQUEST,
    NONE;
}