name: Keycloak Auth Service CI with Gradle and Docker

on:
  push:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew dockerCreateDockerfile

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: champaca-inventory-data-backend
          tags: latest
          registry: ghcr.io
          directory: build/docker
          dockerfile: build/docker/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}